###
# 
GET {{url}}/tasks

###
#
POST {{url}}/tasks
Content-Type: application/json

{
    "name": "do some stuff",
    "completed": true
}

###
#
GET {{url}}/tasks/0815

###
#
PUT {{url}}/tasks/0815
Content-Type: application/json

{
    "name": "do some stuff",
    "completed": true
}

###
#
DELETE  {{url}}/tasks/0815