###
# 
GET {{url}}/tasks

###
# 
GET {{url}}/not/exist

###
#
POST {{url}}/tasks
Content-Type: application/json

{
    "name": "another task",
    "completed": false
}

###
#
POST {{url}}/tasks
Content-Type: application/json

{
    "name": "fgfsgsfgfhfhsfghgfhfghfghfffshzfsjzjzj"
}

###
#
GET {{url}}/tasks/659fbffd0bc27a5d84c20061

###
#
DELETE  {{url}}/tasks/659ff4cc3f4c40c2600ba66c

###
#
PATCH {{url}}/tasks/659ff46916ce9a8090a66db2
Content-Type: application/json

{
    "name": "Hello Task"
}